POST http://localhost:8083/login
Content-Type: application/json

{
  "login": "test",
  "password": "coucou"
}

#POST http://localhost:8083/user/new
#Content-Type: application/json
#
#{
#  "login": "test",
#  "name": "hello",
#  "password": "coucou",
#  "surname": "bonjour"
#}
