POST http://localhost:8083/user/new
Content-Type: application/json

{
  "login": "user",
  "name": "hello",
  "surname": "bonjour",
  "password": "user"

}

###
// Test avec mauvais password
POST http://localhost:8083/login
Content-Type: application/json

{
  "login": "test",
  "password": "coucou"
}

###
// Teste avec le bon mot de passe
POST http://localhost:8083/login
Content-Type: application/json

{
  "login": "user",
  "password": "user"
}

